### DISCUSSION TITLE
Omit SHAs in CHANGELOG

### DISCUSSION THREAD

**Discussion by AshNaz87** [metcalfc/changelog-generator#102] [Ideas]
Hi there,

Lovely project. It would be great if there was an option to omit the SHAs in the CHANGELOG, as I'm looking to make the CHANGELOG as human-friendly as possible

**Comment by metcalfc** [comment]
Have you seen the new'ish (Oct) autogenerated github release notes? https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/

I think you can accomplish a no hash style with a `.github/release.yml` that looks like:

```
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
      - dependabot
  categories:
    - title: Changelog
      labels:
        - "*"
```

This action pre-dates that functionality and my projects don't use a lot of labels and are used to the layout. Otherwise the built feature is nice.
