### ISSUE TITLE
Node version is deprecated warning

### ISSUE THREAD

**Issue by jjoynson-iw** [metcalfc/changelog-generator#164]
Receiving the following issue when using this action: 

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, metcalfc/changelog-generator`

**Comment by metcalfc** [comment]
@jjoynson-iw Thanks. I think I've fixed this in v4. Can you help me verify?

```
- name: Generate changelog
  id: changelog
  uses: metcalfc/changelog-generator@v4.0.0
  with:
    myToken: ${{ secrets.GITHUB_TOKEN }}
```
