### ISSUE TITLE
[error]Not Found

### ISSUE THREAD

**Issue by yi-Xu-0100** [metcalfc/changelog-generator#20]
![image](https://user-images.githubusercontent.com/25523606/91657139-53131980-eaf1-11ea-840a-bd0dbfad6ae4.png)

I don't know why, some errors occurred during my use.
This is my configuration file: 

``` yml
name: autoRelease
on:
  push:
    tags:
      - 'v*'

jobs:
  autoRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
```

According to my investigation, `${{ secrets.GITHUB_TOKEN }}` here does not need to be added, it is generated by default, so I have not done anything except add this file.
If I did something wrong, please let me know, thank you for your work and look forward to your reply.
