### ISSUE TITLE
Unable to use short version @v4

### ISSUE THREAD

**Issue by powerman** [metcalfc/changelog-generator#263]
**Describe the bug**
Error: Unable to resolve action `metcalfc/changelog-generator@v4`, unable to find version `v4`

**To Reproduce**
```yaml
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**
It should work using latest v4 version.

**URL to Public action log**
https://github.com/powerman/dockerize/actions/runs/11516609425/job/32059618802

**Additional context**
Similar issue: https://github.com/ast-grep/action/issues/38
