### ISSUE TITLE
Error returned with exit code 128

### ISSUE THREAD

**Issue by Awais6** [metcalfc/changelog-generator#45]

**Comment by Awais6** [comment]
![image](https://user-images.githubusercontent.com/46025225/102900925-cb319080-448e-11eb-9dfe-a53843ac914c.png)

**Comment by metcalfc** [comment]
Can you link to the actions yaml or include it here? Or if the repo is public just point it out?

**Comment by GPMueller** [comment]
I'm getting the same error: https://github.com/GPMueller/imgui-app/runs/2214158188?check_suite_focus=true#step:2:9
The relevant part of the config reads
```
draft-release:
  if: github.event_name == 'push' && startsWith( github.ref, 'refs/tags/' )
  needs: [desktop-app, web-app]
  runs-on: ubuntu-latest
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  steps:
  - name: 📄 Generate a changelog
    id: changelog
    uses: metcalfc/changelog-generator@v1.0.0
    with:
      myToken: ${{ secrets.GITHUB_TOKEN }}
```

Feels like it might be getting called from the wrong directory?
