### ISSUE TITLE
no commit hash url text

### ISSUE THREAD

**Issue by Slluxx** [metcalfc/changelog-generator#53]
Releases have this text for me:
```
* [](http://github.com/../../../) - Update VERSION
* [](http://github.com/../../../) - Update buildRelease.yml
* [](http://github.com/../../../) - Update buildRelease.yml
```

The URL works and is complete but the text is missing, thus its displaying a line as:

* `-` Update VERSION

I am building a release like this (in case this has to do something with it):

```
    - name: Create Release
      run: |
        set -x
        assets=()
        for asset in ./*.zip; do
          assets+=("-a" "$asset")
        done
        hub release create "${assets[@]}" -d -m "Release v${{ steps.set-version.outputs.version }}
        
        ${{ steps.changelog.outputs.changelog }}" "v${{ steps.set-version.outputs.version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by metcalfc** [comment]
Thats odd. So the bit that does the real work here is a one liner in bash:

```
log=$(git log "${base_ref}...${head_ref}" \
  --pretty=format:"* [\`%h\`](http://github.com/${repo_url}/commit/%H) - %s" \
  --reverse)
```

My guess is that the way you're doing the notes is getting wrecked in the shell via expansions. There are backticks in the short hash link so those could be getting evaluated. I'm not sure if there is a better way to escape those in a shell.

Have you considered using a release specific action instead of hub in shell script? https://github.com/marketplace/actions/create-release seems reasonably aligned:

```
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "./*zip"
        name: "Release v${{ steps.set-version.outputs.version }}"
        body: "${{ steps.changelog.outputs.changelog }}"
        tag: "v${{ steps.set-version.outputs.version }}"
        token: ${{ secrets.GITHUB_TOKEN }}
```
